echo off
echo ==========CONSOLE==========
cd compile_console
call startConsole.bat
cd ..\
echo ==========ANT==========
cd compile_ant
call startAnt.bat
cd ..\
echo ==========MVN==========
cd compile_maven
call startMaven.bat
cd ..\
